name       : python-attrs
version    : 20.3.0
release    : 9
source     :
    - https://github.com/python-attrs/attrs/archive/20.3.0.tar.gz : c7d2ef493768bfea33cd5d8cbd2a6c2ddf229d5e8c3a79aefa67d1daf1e9d96d
license    : MIT
component  : programming.python
summary    : Python attributes without boilerplate.
description: |
    Python attributes without boilerplate.
builddeps  :
    - python-hypothesis
    - python-pytest
    - python-setuptools
    - python-zope.interface
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
#check      : |
#    %python_test
#    %python3_test
