name       : python-attrs
version    : 19.3.0
release    : 7
source     :
    - https://github.com/python-attrs/attrs/archive/19.3.0.tar.gz : 165e38891eedc55c02d37075dec0b633d0512ce6e505aa75afef5bdc31ee0f99
license    : MIT
component  : programming.python
summary    : Python attributes without boilerplate.
description: |
    Python attributes without boilerplate.
builddeps  :
    - python-hypothesis
    - python-pytest
    - python-setuptools
    - python-zope.interface
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
#check      : |
#    pushd $PKG_BUILD_DIR/py2build
#        PYTHONPATH=$PWD/build/lib py.test
#    popd

#    pushd $PKG_BUILD_DIR/py3build
#        PYTHONPATH=$PWD/build/lib py.test3
#    popd
