name       : python-attrs
version    : 21.4.0
release    : 18
source     :
    - https://github.com/python-attrs/attrs/archive/refs/tags/21.4.0.tar.gz : 5bd6d2938b7e8019e319b7f451f4ec3a5ef6293b228146387d002311ae9b920d
license    : MIT
component  : programming.python
summary    : Python attributes without boilerplate.
description: |
    Python attributes without boilerplate.
builddeps  :
    - python-hypothesis
    - python-pytest
    - python-zope.interface
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    # py2 testsuite requires hypothesis which doesn't have py2 support
    %python3_test pytest3
