name       : python-attrs
version    : 21.2.0
release    : 11
source     :
    - https://github.com/python-attrs/attrs/archive/refs/tags/21.2.0.tar.gz : 12cca0d697de845fd74b6b5482218988ee1415c27d3bb31503f66c2a3592b77c
license    : MIT
component  : programming.python
summary    : Python attributes without boilerplate.
description: |
    Python attributes without boilerplate.
builddeps  :
    - python-hypothesis
    - python-pytest
    - python-setuptools
    - python-zope.interface
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
check      : |
    %python_test pytest
    %python3_test pytest3
