name       : python-attrs
version    : 17.2.0
release    : 2
source     :
    - https://pypi.python.org/packages/be/41/e909cb6d901e9689da947419505cc7fb7d242a08a62ee221fce6a009a523/attrs-17.2.0.tar.gz : 5d4d1b99f94d69338f485984127e4473b3ab9e20f43821b0e546cc3b2302fd11
license    : MIT
component  : programmign.python
summary    : Python attributes without boilerplate.
description: |
    Python attributes without boilerplate.
builddeps  :
    - pkgconfig(python-2.7)
    - pkgconfig(python-3.5)
    - python-setuptools
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
