name       : python-attrs
version    : 15.2.0
release    : 1
source     :
    - https://pypi.python.org/packages/source/a/attrs/attrs-15.2.0.tar.gz : 9f895d2ecefa0be054e29375769f1d0ee88e93ce820088cf5c49390529bf7ee7
license    : MIT
summary    : Python attributes without boilerplate.
description: |
    Python attributes without boilerplate.
builddeps  :
    - pkgconfig(python-2.7)
    - pkgconfig(python-3.5)
    - python-setuptools
build      : |
    for py in "python" "python3" ; do
        ${py} setup.py build
    done
install    : |
    for py in "python" "python3" ; do
        ${py} setup.py install --root=%installroot% --no-compile -O0
    done
